import { CONNECTION_STATE, SELECT_ITILE, TileColor, SideColors, TouchResponse, ShakeResponse, SidePairResponse, PairedTilesResponse, OnlineTilesResponse, StepChangeResponse, BatteryStatusResponse, LOG_REACTION_TIME, TIMEOUT_DELAY, TIMEOUT_RESPONSE, SOUND_TRACK, VIBRATION_PATTERN, REPEAT_COUNT, TOGGLE_SENSOR, GAME_STATUS, FEEDBACK_STATUS } from './constants';
export declare class ITilesBLEManager {
    private device;
    private server;
    private service;
    private rxCharacteristic;
    private txCharacteristic;
    private connectionState;
    private onConnectionStateChangedCallback?;
    private onDataReceivedCallback?;
    private onMasterTilesDiscoveredCallback?;
    private onTouchCallback?;
    private onShakeCallback?;
    private onSidePairedCallback?;
    private onStepChangedCallback?;
    private onTileTimedOutCallback?;
    private onPairedTileListReceivedCallback?;
    private onOnlineTileStatusReceivedCallback?;
    private onBatteryStatusReceivedCallback?;
    constructor();
    onConnectionStateChanged(callback: (state: CONNECTION_STATE) => void): void;
    onDataReceived(callback: (data: string) => void): void;
    onMasterTilesDiscovered(callback: (devices: BluetoothDevice[]) => void): void;
    onTouch(callback: (response: TouchResponse) => void): void;
    onShake(callback: (response: ShakeResponse) => void): void;
    onSidePaired(callback: (response: SidePairResponse) => void): void;
    onStepChanged(callback: (response: StepChangeResponse) => void): void;
    onTileTimedOut(callback: () => void): void;
    onPairedTileListReceived(callback: (response: PairedTilesResponse) => void): void;
    onOnlineTileStatusReceived(callback: (response: OnlineTilesResponse) => void): void;
    onBatteryStatusReceived(callback: (response: BatteryStatusResponse) => void): void;
    scan(): Promise<BluetoothDevice[]>;
    requestDevice(): Promise<BluetoothDevice>;
    connect(device?: BluetoothDevice): Promise<void>;
    disconnect(): Promise<void>;
    private handleDisconnection;
    private startNotifications;
    private handleNotification;
    private decodeMessage;
    private handleTouchResponse;
    private handleShakeResponse;
    private handleSidePairResponse;
    private handlePairedTilesResponse;
    private handleOnlineTilesResponse;
    private handleStepChangeResponse;
    private handleBatteryStatusResponse;
    private sendCommand;
    pairTiles(masterTileMacAddress: number[], tileId?: SELECT_ITILE): Promise<void>;
    unpairTile(tileId: SELECT_ITILE): Promise<void>;
    clearMacList(): Promise<void>;
    queryPairedTiles(): Promise<void>;
    queryOnlineTiles(tileId?: SELECT_ITILE): Promise<void>;
    triggerLight(color: TileColor, offAfterSeconds: TIMEOUT_DELAY, logReactionTime: LOG_REACTION_TIME, timeoutResponse: TIMEOUT_RESPONSE, tileId: SELECT_ITILE): Promise<void>;
    triggerSound(soundTrackId: SOUND_TRACK, repeatCount: REPEAT_COUNT, logReactionTime: LOG_REACTION_TIME, timeoutResponse: TIMEOUT_RESPONSE, tileId: SELECT_ITILE): Promise<void>;
    triggerVibration(vibrationPattern: VIBRATION_PATTERN, repeatCount: REPEAT_COUNT, logReactionTime: LOG_REACTION_TIME, timeoutResponse: TIMEOUT_RESPONSE, tileId: SELECT_ITILE): Promise<void>;
    triggerSideLight(sideColors: SideColors, offAfterSeconds: TIMEOUT_DELAY, logReactionTime: LOG_REACTION_TIME, timeoutResponse: TIMEOUT_RESPONSE, tileId: SELECT_ITILE): Promise<void>;
    triggerLightSoundVibration(lightColor: TileColor, timeoutDelay: TIMEOUT_DELAY, soundTrackId: SOUND_TRACK, vibrationPattern: VIBRATION_PATTERN, repeatCount: REPEAT_COUNT, logReactionTime: LOG_REACTION_TIME, timeoutResponse: TIMEOUT_RESPONSE, tileId: SELECT_ITILE): Promise<void>;
    triggerSideLightSoundVibration(sideColors: SideColors, timeoutDelay: TIMEOUT_DELAY, soundTrackId: SOUND_TRACK, vibrationPattern: VIBRATION_PATTERN, repeatCount: REPEAT_COUNT, logReactionTime: LOG_REACTION_TIME, timeoutResponse: TIMEOUT_RESPONSE, tileId: SELECT_ITILE): Promise<void>;
    turnOffLight(tileId: SELECT_ITILE): Promise<void>;
    stopEffect(tileId: SELECT_ITILE): Promise<void>;
    toggleShakeSensor(toggle: TOGGLE_SENSOR, tileId: SELECT_ITILE): Promise<void>;
    setShakeThreshold(threshold: number, tileId: SELECT_ITILE): Promise<void>;
    toggleTouchSensor(toggle: TOGGLE_SENSOR, tileId: SELECT_ITILE): Promise<void>;
    confirmAssignment(tileId: SELECT_ITILE): Promise<void>;
    gameInProgress(gameStatus: GAME_STATUS, tileId: SELECT_ITILE): Promise<void>;
    assignFeedback(feedbackStatus: FEEDBACK_STATUS, color: TileColor, soundTrackId: SOUND_TRACK, vibrationPattern: VIBRATION_PATTERN, timeoutDelay: TIMEOUT_DELAY, tileId: SELECT_ITILE): Promise<void>;
    getBattery(tileId: SELECT_ITILE): Promise<void>;
    private updateConnectionState;
    getConnectionState(): CONNECTION_STATE;
    isConnected(): boolean;
    private bytesToHex;
    static hexToBytes(hex: string): Uint8Array;
}
